const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
let isRegister = false, state = { accounts: [], transactions: [] };
const api = async (url, options = {}) => { const token = localStorage.getItem('bankToken'); const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Something went wrong.'); return data; };
const money = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(n));
const toast = message => { const t = $('#toast'); t.textContent = message; t.classList.remove('hidden'); setTimeout(() => t.classList.add('hidden'), 3200); };
const showModal = id => $(`#${id}`).classList.remove('hidden'); const closeModals = () => $$('.modal').forEach(m => m.classList.add('hidden'));

function accountCard(a) { return `<article class="account-card"><div class="account-top"><span class="account-icon">▣</span><span class="badge">Active</span></div><h3>${a.account_type} account</h3><small>${a.account_number}</small><h4>${money(a.balance)}</h4><div class="card-actions"><button onclick="openTransaction(${a.id},'Deposit')">+ Deposit</button><button onclick="openTransaction(${a.id},'Withdraw')">− Withdraw</button><button class="delete" onclick="deleteAccount(${a.id})">Delete</button></div></article>`; }
function transactionsHtml(transactions) { if (!transactions.length) return '<div class="empty">No transactions yet. Your activity will appear here.</div>'; return transactions.map(t => `<div class="transaction ${t.type === 'Withdraw' ? 'withdraw' : ''}"><span class="transaction-icon">${t.type === 'Deposit' ? '↓' : '↑'}</span><div class="transaction-info"><b>${t.type}${t.note ? ` · ${t.note}` : ''}</b><small>${t.account_number} · ${new Date(t.created_at).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</small></div><span class="transaction-amount">${t.type === 'Deposit' ? '+' : '−'}${money(t.amount)}</span></div>`).join(''); }
function render() { $('#totalBalance').textContent = money(state.totalBalance || 0); const cards = state.accounts.length ? state.accounts.map(accountCard).join('') : '<div class="empty">No bank account yet. Create your first account to get started.</div>'; $('#accountGrid').innerHTML = cards; $('#allAccounts').innerHTML = cards; $('#recentTransactions').innerHTML = transactionsHtml(state.transactions.slice(0, 5)); $('#fullTransactions').innerHTML = transactionsHtml(state.transactions); }
async function loadDashboard() { try { state = await api('/api/dashboard'); render(); } catch (e) { localStorage.removeItem('bankToken'); showAuth(); toast(e.message); } }
function showAuth() { $('#appView').classList.add('hidden'); $('#authView').classList.remove('hidden'); }
function showApp() { const user = JSON.parse(localStorage.getItem('bankUser') || '{}'); $('#userName').textContent = user.name || 'User'; $('#initial').textContent = (user.name || 'U')[0].toUpperCase(); $('#authView').classList.add('hidden'); $('#appView').classList.remove('hidden'); loadDashboard(); }
function setPage(page) { $$('.page').forEach(p => p.classList.toggle('hidden', p.id !== page)); $$('.nav[data-page]').forEach(b => b.classList.toggle('active', b.dataset.page === page)); $('#pageTitle').textContent = page === 'overview' ? 'Good morning' : page === 'accounts' ? 'My accounts' : 'Transaction history'; $('.sidebar').classList.remove('open'); }
window.openTransaction = (id, type) => { $('#transactionAccount').value = id; $('#transactionType').value = type; $('#transactionLabel').textContent = type.toUpperCase(); $('#transactionTitle').textContent = `${type} money`; $('#transactionSubmit').textContent = `${type} now`; $('#transactionForm').reset(); $('#transactionAccount').value = id; $('#transactionType').value = type; showModal('transactionModal'); };
window.deleteAccount = async id => { if (!confirm('Delete this account and all its transactions?')) return; try { toast((await api(`/api/accounts/${id}`, { method: 'DELETE' })).message); loadDashboard(); } catch (e) { toast(e.message); } };

$('#authForm').addEventListener('submit', async e => { e.preventDefault(); const body = { email: $('#email').value, password: $('#password').value }; if (isRegister) body.name = $('#name').value; try { const data = await api(`/api/auth/${isRegister ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(body) }); localStorage.setItem('bankToken', data.token); localStorage.setItem('bankUser', JSON.stringify(data.user)); showApp(); toast(isRegister ? 'Account created successfully!' : 'Welcome back!'); } catch (error) { toast(error.message); } });
function toggleAuth() { isRegister = !isRegister; $('#nameField').classList.toggle('hidden', !isRegister); $('#authTitle').textContent = isRegister ? 'Create your account' : 'Welcome back'; $('#authSubtitle').textContent = isRegister ? 'Start managing your money today.' : 'Login to access your dashboard.'; $('#authSubmit').innerHTML = isRegister ? 'Create account <span>→</span>' : 'Login to dashboard <span>→</span>'; $('#switchCopy').innerHTML = isRegister ? 'Already a member? <button id="switchAuth">Login instead</button>' : 'New to SecureBank? <button id="switchAuth">Create an account</button>'; $('#switchAuth').addEventListener('click', toggleAuth); }
$('#switchAuth').addEventListener('click', toggleAuth);
$('#showPassword').addEventListener('click', () => { const p = $('#password'); p.type = p.type === 'password' ? 'text' : 'password'; });
$$('.nav[data-page]').forEach(b => b.addEventListener('click', () => setPage(b.dataset.page))); $$('[data-page-link]').forEach(b => b.addEventListener('click', () => setPage(b.dataset.pageLink))); $$('[data-open]').forEach(b => b.addEventListener('click', () => showModal(b.dataset.open))); $$('.close').forEach(b => b.addEventListener('click', closeModals)); $$('.modal').forEach(m => m.addEventListener('click', e => { if (e.target === m) closeModals(); }));
$('#accountForm').addEventListener('submit', async e => { e.preventDefault(); try { toast((await api('/api/accounts', { method: 'POST', body: JSON.stringify({ accountType: $('#accountType').value, openingBalance: $('#openingBalance').value }) })).message); closeModals(); e.target.reset(); loadDashboard(); } catch (error) { toast(error.message); } });
$('#transactionForm').addEventListener('submit', async e => { e.preventDefault(); const id = $('#transactionAccount').value; try { toast((await api(`/api/accounts/${id}/transaction`, { method: 'POST', body: JSON.stringify({ type: $('#transactionType').value, amount: $('#transactionAmount').value, note: $('#transactionNote').value }) })).message); closeModals(); loadDashboard(); } catch (error) { toast(error.message); } });
$('#accountSearch').addEventListener('input', async e => { const q = e.target.value.trim(); if (!q) return ($('#allAccounts').innerHTML = state.accounts.length ? state.accounts.map(accountCard).join('') : '<div class="empty">No bank account yet.</div>'); try { const data = await api(`/api/accounts/search?q=${encodeURIComponent(q)}`); $('#allAccounts').innerHTML = data.length ? data.map(accountCard).join('') : '<div class="empty">No matching account found.</div>'; } catch (error) { toast(error.message); } });
$('#logout').addEventListener('click', () => { localStorage.removeItem('bankToken'); localStorage.removeItem('bankUser'); showAuth(); }); $('#menuButton').addEventListener('click', () => $('.sidebar').classList.toggle('open'));
localStorage.getItem('bankToken') ? showApp() : showAuth();
